package com.drools.demo

import org.z.entities.rules.engine.Boat
import org.z.entities.rules.engine.Fact  
import org.z.entities.rules.engine.RuleTrigger 
import org.z.entities.rules.engine.types.Tack  
import static org.z.entities.rules.engine.utils.Utils.getOverlappedForBoats  
import static org.z.entities.rules.engine.utils.Utils.getWindwardForBoats

rule "Opposite Tack boat1 tack is STARBOARD"
dialect "mvel" 
   when 
      $fact:Fact($fact.boat1.tack != $fact.boat2.tack && 
                 $fact.boat1.tack == Tack.STARBOARD) 
   then
   	  $fact.boat1.keepMove = true;
   	  $fact.boat2.keepMove = false;   
   	  insert(new RuleTrigger("ASSAF")); 
end	

rule "Opposite Tack boat1 tack is PORT" 
no-loop
dialect "mvel" 
   when 
      $fact:Fact( $fact.boat1.tack != $fact.boat2.tack && 
                   $fact.boat1.tack == Tack.PORT) 
   then
 	  $fact.boat1.keepMove = false;
   	  $fact.boat2.keepMove = true;  
   	   insert(new RuleTrigger("ASSAF"));   
end		
	
rule "Same Tack Not Overlapped boat2 is clear ahead" 
dialect "mvel" 
no-loop 
when 
	 $fact:Fact($fact.boat1.tack == $fact.boat2.tack &&
			    $fact.overLappedInd == 1 )    
then 
		System.out.println("boat2 is clear ahead");
		$fact.boat1.keepMove = false;
		$fact.boat2.keepMove = true;  
		insert(new RuleTrigger("ASSAF"));
end

rule "Same Tack Not Overlapped boat1 is clear ahead"
dialect "mvel" 
no-loop 
when 
    $fact:Fact($fact.boat1.tack == $fact.boat2.tack &&
    		   $fact.overLappedInd == -1 )   
then  
		System.out.println("boat1 is clear ahead");
		$fact.boat1.keepMove = true;
		$fact.boat2.keepMove = false;  
		insert(new RuleTrigger("ASSAF"));
end


rule "Same Tack Overlapped boat1 is windward"  
dialect "mvel" 
when 
    $fact:Fact($fact.boat1.tack == $fact.boat2.tack &&
               $fact.overLappedInd == 0 &&
               $fact.windwardInd == -1)   
then  
		System.out.println("boat1 is windward");
		$fact.boat1.keepMove = false;
		$fact.boat2.keepMove = true;  
end

rule "Same Tack Overlapped boat2 is windward"  
dialect "mvel" 
when 
    $fact:Fact($fact.boat1.tack == $fact.boat2.tack &&
               $fact.overLappedInd == 0 &&
               $fact.windwardInd == 1)    
then  
		System.out.println("boat2 is windward");
		$fact.boat1.keepMove = true;
		$fact.boat2.keepMove = false;  
end
 